### PR TITLE
Fix LOC centimetre parser to handle decimetres properly.

### PR DESCRIPTION
**Pull request by FGasper**
Issue #121: Previously “0.1” was parsed as “0.01”; this fixes that.

### CODE REVIEW

**Comment by FGasper** [comment]
What would be the simplest way to add a test for this? (I confirmed via my test program that this does solve the problem.)

**Comment by FGasper** [comment]
I’ve added a test but am unsure of the proper format for it; tpkg creates an archive, but the repo’s existing tests are all directories.

**Comment by FGasper** [comment]
It _might_ be better to replace the cm parser with a hard-coded lookup, since there are only 100 possible numbers here. But this is a conservative fix.

**Comment by wtoorop** [comment]
Absolutely! Will merge with slightly modified test package so it gets called in the right moment.

**Pull request merged**
