### PR TITLE
Address several issues with the ultimate goal being to fix Coverity cited problems

### PR DESCRIPTION
**Pull request by ngie-eign**
- Update `.gitignore` to ignore more build generated files.
- Fix typos (`the the` -> `the`).
- Fix a memory leak.
- Fix a bad type/potential unsigned integer overflow issue.

### CODE REVIEW

**Comment by wcawijngaards** [comment]
This set of changes looks nice to me. Unbound has similar issues, because it has the same code in certain places, it needs the memory leak fix and some of the spelling fixes. I have created commits to the unbound code base to fix them, in https://github.com/NLnetLabs/unbound/commit/3cad5818a1b894415c3cd85987320e79717cf5c0 and https://github.com/NLnetLabs/unbound/commit/1974732d19229a6d885c2926db96e447590e5b86 .

**Comment by ngie-eign** [comment]
> This set of changes looks nice to me. Unbound has similar issues, because it has the same code in certain places, it needs the memory leak fix and some of the spelling fixes. I have created commits to the unbound code base to fix them, in [NLnetLabs/unbound@3cad581](https://github.com/NLnetLabs/unbound/commit/3cad5818a1b894415c3cd85987320e79717cf5c0) and [NLnetLabs/unbound@1974732](https://github.com/NLnetLabs/unbound/commit/1974732d19229a6d885c2926db96e447590e5b86) .

Much appreciated! I looked at those PRs -- do I need to submit entries to the ChangeLog as well for the proposed changes, or is that something maintainers can handle?

**Comment by wtoorop** [comment]
> Much appreciated! I looked at those PRs -- do I need to submit entries to the ChangeLog as well for the proposed changes, or is that something maintainers can handle?

I should be able to handle that :grin: . How would you prefer to be credited? As ngie-eign or with your full name.
Cheers!

**Comment by ngie-eign** [comment]
]


> > Much appreciated! I looked at those PRs -- do I need to submit entries to the ChangeLog as well for the proposed changes, or is that something maintainers can handle?
> 
> I should be able to handle that 😁 . How would you prefer to be credited? As ngie-eign or with your full name. Cheers!

Thanks! Could you please use my legal name (Enji Cooper) :)?

**Review by wtoorop — APPROVED** [review]
This all looks fine. Thanks.

**Pull request merged**
