### PR TITLE
Update python configuration, support platform site dir

### PR DESCRIPTION
**Pull request by pemensik**
Update to the most recent ax_python_devel.m4 from autoconf-archive 2022.09.03. It reports two separate directories, one for platform independent files, another for platform specific files.

Make sure native code library installs into platform site directory. Python modules can be installed into common site directory. Should work on python 3.12, which removes distutils module completely.

Attempts to fix bug: https://bugzilla.redhat.com/show_bug.cgi?id=2155003

### CODE REVIEW

**Comment by pemensik** [comment]
Oh, the strange thing is update of ``ax_python_devel.m4`` only has changed the destination directories from platform-specific to platform independent location. At least for ``_ldns.so`` this is clearly wrong. I am not sure where should those files belong. Perhaps it should be split into two separate commits. One with minimal only change supporting python 3.12, the second changing *ldnsx* module to be installed into platform independent directory, but *ldns* module and *_ldns.so* should be installed together to platform specific directory.

**Comment by pemensik** [comment]
Platform specific directory is okay according to [RH bug comment 3](https://bugzilla.redhat.com/show_bug.cgi?id=2155003#c3). Therefore I removed split into python-only and platform directory. And keep just the most simple change building and installing it to the same place as before.

**Comment by pemensik** [comment]
This change is required to build with python 3.12. Is there anything needed? It is already as minimal as possible.

**Comment by wtoorop** [comment]
> This change is required to build with python 3.12. Is there anything needed? It is already as minimal as possible.

Petr nothing, this looks like a clear fix. Thanks!

**Comment by eli-schwartz** [comment]
python 3.12 has been out for a while now, and this change is necessary to compile with it. Any news on tagging a new release? :)

**Comment by wtoorop** [comment]
Thanks. I will start working on a release very soon..

**Pull request merged**
